name: Check code quality for Currency Converter
on:
  push:
    paths:
      - currency_converter/*/**

defaults:
  run:
    working-directory: currency_converter

jobs:
  format-code:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v2

      - name: Install flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'

      - name: Setup project
#        working-directory: currency_converter
        run: flutter pub get

      - name: Format code
#        working-directory: currency_converter
        run: flutter format -l 120 --set-exit-if-changed .


  analyze-code:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v2

      - name: Install flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'

      - name: Setup project
#        working-directory: currency_converter
        run: flutter pub get

      - name: Analyze code
#        working-directory: currency_converter
        run: flutter format analyze