name: Check code quality for TicTacToe
on:
  push:
    paths:
      - tic_tac_toe/*/**

defaults:
  run:
    working-directory: tic_tac_toe

jobs:
  format-code:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v2

      - name: Install flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'

      - name: Setup project
        run: flutter pub get

      - name: Format code
        run: flutter format -l 120 --set-exit-if-changed .


  analyze-code:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v2

      - name: Install flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'

      - name: Setup project
        run: flutter pub get

      - name: Analyze code
        run: flutter format analyze